.TH "QLIQUIDSFZ" "1" 
.SH "NAME" 
qliquidsfz \(em GUI to libliquidsfz, an SFZ synth player.
.SH "SYNOPSIS" 
.PP 
\fBqliquidsfz\fR [file.sfz] 
.SH "DESCRIPTION" 
.PP 
This manual page documents the \fBqliquidsfz\fR program. 
.PP 
\fBqliquidsfz\fR is a graphical program that interfaces with libliquidsfz,
an SFZ synth player. SFZ files are sampler data descriptions, coming along
with sample data, which are generally superior to the SF2 soundfont format.
 
.PP 
\fBqliquidsfz\fR allow the user to select an SFZ file to load and play
through the jack audio connection kit interface, with a MIDI keyboard.
 
.\" created by instant / docbook-to-man 
